spring:
  application:
    name: werewolf
  data:
    redis:
      host: 124.71.191.180
      port: 9379
      database: 1
      password: yuan001206mu
      timeout: 1800000
      lettuce:
        pool:
          max-active: 30
          max-wait: -1
          max-idle: 10
          min-idle: 0
server:
  port: 9010
sa-token:
  token-name: werewolf
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: simple-uuid
  is-log: true